# Example: Kuala Lumpur (dest_id -372490, matching your itinerary output). 
# Replaces the Tokyo mock data.
SPONSORED_MOCK_HOTELS: list[dict] = [
    {
        "dest_id": "-372490",
        "hotel_id": "sponsored-kl-001",
        "hotel_name": "Grand Hyatt Kuala Lumpur",
        "address": "12, Jalan Pinang",
        "city": "Kuala Lumpur",
        "latitude": 3.1528,
        "longitude": 101.7119,
        "star_rating": 5,
        "price_per_night": 185.00,
        "currency": "USD",
        "rating": 9.2,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        "free_cancellation": True,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": "Sponsored Rate",
    },
    {
        "dest_id": "-372490",
        "hotel_id": "sponsored-kl-002",
        "hotel_name": "Traders Hotel, Kuala Lumpur",
        "address": "Kuala Lumpur City Centre",
        "city": "Kuala Lumpur",
        "latitude": 3.1537,
        "longitude": 101.7150,
        "star_rating": 5,
        "price_per_night": 149.50,
        "currency": "USD",
        "rating": 9.0,
        "image_url": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
        "free_cancellation": True,
        "no_prepayment": False,
        "is_sold_out": False,
        "room_name": "Sponsored Rate",
    },
    {
        "dest_id": "-372490",
        "hotel_id": "sponsored-kl-003",
        "hotel_name": "Banyan Tree Kuala Lumpur",
        "address": "2 Jalan Conlay",
        "city": "Kuala Lumpur",
        "latitude": 3.1504,
        "longitude": 101.7145,
        "star_rating": 5,
        "price_per_night": 210.00,
        "currency": "USD",
        "rating": 9.4,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
        "free_cancellation": True,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": "Sponsored Rate",
    },
]

# ==========================================
# Non-sponsored (regular) mock hotels
# ==========================================
NOT_SPONSORED_MOCK_HOTELS: list[dict] = [
    {
        "dest_id": "-372490",
        "hotel_id": "regular-kl-001",
        "hotel_name": "EQ Kuala Lumpur",
        "address": "Equatorial Plaza, Jalan Sultan Ismail",
        "city": "Kuala Lumpur",
        "latitude": 3.1531,
        "longitude": 101.7088,
        "star_rating": 5,
        "price_per_night": 165.00,
        "currency": "USD",
        "rating": 9.1,
        "image_url": "https://images.unsplash.com/photo-1590073844006-33379778ae09?w=800",
        "free_cancellation": True,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": "Deluxe King Room",
        "is_sponsored": False,
    },
    {
        "dest_id": "-372490",
        "hotel_id": "regular-kl-002",
        "hotel_name": "Mandarin Oriental, Kuala Lumpur",
        "address": "Kuala Lumpur City Centre",
        "city": "Kuala Lumpur",
        "latitude": 3.1556,
        "longitude": 101.7106,
        "star_rating": 5,
        "price_per_night": 195.50,
        "currency": "USD",
        "rating": 8.9,
        "image_url": "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
        "free_cancellation": False,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": "Park View Room",
        "is_sponsored": False,
    },
    {
        "dest_id": "-372490",
        "hotel_id": "regular-kl-003",
        "hotel_name": "RuMa Hotel and Residences",
        "address": "7 Jalan Kia Peng",
        "city": "Kuala Lumpur",
        "latitude": 3.1517,
        "longitude": 101.7128,
        "star_rating": 5,
        "price_per_night": 142.00,
        "currency": "USD",
        "rating": 9.3,
        "image_url": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800",
        "free_cancellation": True,
        "no_prepayment": False,
        "is_sold_out": False,
        "room_name": "Grand Studio",
        "is_sponsored": False,
    },
    {
        "dest_id": "-372490",
        "hotel_id": "regular-kl-004",
        "hotel_name": "W Kuala Lumpur",
        "address": "121 Jalan Ampang",
        "city": "Kuala Lumpur",
        "latitude": 3.1593,
        "longitude": 101.7082,
        "star_rating": 5,
        "price_per_night": 220.00,
        "currency": "USD",
        "rating": 8.8,
        "image_url": "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
        "free_cancellation": True,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": "Spectacular Room",
        "is_sponsored": False,
    },
    {
        "dest_id": "-372490",
        "hotel_id": "regular-kl-005",
        "hotel_name": "Concorde Hotel Kuala Lumpur",
        "address": "2 Jalan Sultan Ismail",
        "city": "Kuala Lumpur",
        "latitude": 3.1554,
        "longitude": 101.7059,
        "star_rating": 4,
        "price_per_night": 75.00,
        "currency": "USD",
        "rating": 8.4,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        "free_cancellation": False,
        "no_prepayment": False,
        "is_sold_out": True,
        "room_name": "Superior Room",
        "is_sponsored": False,
    },
    {
        "dest_id": "-372490",
        "hotel_id": "regular-kl-006",
        "hotel_name": "Pullman Kuala Lumpur City Centre",
        "address": "4 Jalan Conlay",
        "city": "Kuala Lumpur",
        "latitude": 3.1500,
        "longitude": 101.7138,
        "star_rating": 5,
        "price_per_night": 110.00,
        "currency": "USD",
        "rating": 8.6,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
        "free_cancellation": True,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": "Premium Deluxe Room",
        "is_sponsored": False,
    },
]

# ==========================================
# Mock per-hotel room prices
# ==========================================
def _mock_room_blocks(hotel: dict) -> dict:
    base = hotel["price_per_night"]
    currency = hotel.get("currency", "USD")
    free_cancel = bool(hotel.get("free_cancellation", False))
    return {
        "rooms": [
            {
                "room_name": hotel.get("room_name") or "Standard Room",
                "price_per_night": round(base, 2),
                "currency": currency,
                "max_occupancy": 2,
                "breakfast_included": False,
                "is_refundable": free_cancel,
                "cancellation_policy": (
                    "Free cancellation until 24h before check-in" if free_cancel else "Non-refundable"
                ),
            },
            {
                "room_name": "Deluxe Room",
                "price_per_night": round(base * 1.3, 2),
                "currency": currency,
                "max_occupancy": 3,
                "breakfast_included": True,
                "is_refundable": True,
                "cancellation_policy": "Free cancellation until 24h before check-in",
            },
            {
                "room_name": "Executive Suite",
                "price_per_night": round(base * 1.7, 2),
                "currency": currency,
                "max_occupancy": 4,
                "breakfast_included": True,
                "is_refundable": False,
                "cancellation_policy": "Non-refundable",
            },
        ]
    }

MOCK_ROOM_PRICES_RAW: dict[str, dict] = {
    h["hotel_id"]: _mock_room_blocks(h)
    for h in SPONSORED_MOCK_HOTELS + NOT_SPONSORED_MOCK_HOTELS
}